'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDown, ArrowUpRight, ArrowRight, MapPin, X, Pause, Play } from 'lucide-react';
import { Dialog, DialogContent, DialogClose } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { BookingForm } from '@/components/booking-form';
import { SiteHeader, SiteFooter } from '@/components/site-shell';
import { visitRules } from '@/lib/site';

const venues = [
 {id:'chkalovskaya',line:5,color:'#8b4a96',name:'Чкаловская',address:'Газовая улица, 10, корпус Ж',place:'м. Чкаловская / Петроградская',kids:'6–13 лет',sessions:[{days:'Понедельник, пятница',adult:'20:30 — 21:30',child:'19:30 — 20:30'}]},
 {id:'lesnaya',line:1,color:'#d32932',name:'Лесная',address:'Улица Карбышева, 9',place:'Спортивный центр «Триада»',kids:'7–13 лет',sessions:[{days:'Вторник, четверг',adult:'18:30 — 19:30',child:'18:30 — 19:30'}]},
 {id:'vyborgskaya',line:1,color:'#d32932',name:'Выборгская',address:'Евпаторийский переулок, 7Д',place:'Спортивный центр BASKET SPACE',kids:null,sessions:[{days:'Воскресенье',adult:'18:00 — 19:00',child:null}]},
 {id:'begovaya',line:3,color:'#178f54',name:'Беговая',address:'Приморский проспект, 72',place:'ТРК «Питерлэнд», 3 этаж',kids:'7–13 лет',sessions:[{days:'Понедельник',adult:'19:00 — 20:00',child:'18:00 — 19:00'},{days:'Суббота',adult:'20:00 — 21:00',child:'20:00 — 21:00'}]},
 {id:'park',line:2,color:'#2373b6',name:'Парк Победы',address:'Бассейная улица, 38к',place:'Спортивный центр URBO',kids:'7–13 лет',sessions:[{days:'Среда',adult:'19:00 — 20:00',child:'19:00 — 20:00'}]},
];
export default function Home() {
 const [venueId,setVenueId]=useState('chkalovskaya');
 const [audience,setAudience]=useState('adult');
 const [booking,setBooking]=useState(false);
 const [program,setProgram]=useState('Баскетбольные навыки');
 const videoRef=useRef<HTMLVideoElement>(null);
 const [videoPlaying,setVideoPlaying]=useState(false);
 const [videoReady,setVideoReady]=useState(false);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{const video=videoRef.current;if(!video)return;if(query.matches)video.pause();else void video.play().catch(()=>setVideoPlaying(false));};update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 const toggleVideo=()=>{const video=videoRef.current;if(!video)return;if(video.paused)void video.play().catch(()=>setVideoPlaying(false));else video.pause()};

 const openBooking=(choice='Баскетбольные навыки',location?:string)=>{if(location)setVenueId(location);setProgram(choice);setBooking(true)};
 useEffect(()=>{
  type ToolContext={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document & {modelContext?:ToolContext}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'show_training_schedule',title:'Показать расписание тренировок',description:'Перейти к расписанию зала. Все возрастные группы видны одновременно. Не создаёт запись и не отправляет сообщения.',inputSchema:{type:'object',properties:{venue:{type:'string',enum:venues.map(v=>v.id)}},required:['venue'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=input as {venue?:string};if(!value||!venues.some(v=>v.id===value.venue))throw new Error('Укажите существующий зал.');const chosen=venues.find(v=>v.id===value.venue)!;flushSync(()=>setVenueId(chosen.id));document.getElementById('venue-'+chosen.id)?.scrollIntoView({behavior:'instant'});return {venue:chosen.name,address:chosen.address,sessions:chosen.sessions.map(s=>({days:s.days,children:s.child,adults:s.adult})),bookingCreated:false}}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* The site works without the optional browser API. */}
  return()=>lifecycle.abort();
 },[]);
 return <div id="top" className="home-page">
  <a className="announcement" href="#schedule">Новый сезон 2026 / 27 <span>Первая тренировка — бесплатно</span><ArrowUpRight size={14}/></a>
  <SiteHeader onBooking={()=>openBooking()}/>
  <main id="main">
   <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src="/basketspb/images/hero-poster.jpg" alt="Баскетбольная тренировка" fetchPriority="high" width="1600" height="900"/><video ref={videoRef} className={`hero-video ${videoReady?'is-ready':''}`} muted loop playsInline preload="metadata" poster="/basketspb/images/hero-poster.jpg" aria-label="Видео баскетбольной тренировки" onCanPlay={()=>setVideoReady(true)} onPlaying={()=>setVideoPlaying(true)} onPause={()=>setVideoPlaying(false)} onError={()=>{setVideoReady(false);setVideoPlaying(false)}}><source src="/basketspb/videos/hero.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-main"><h1 id="hero-title">БАСКЕТБОЛ<br/>В СПБ.<span className="hero-audience">Для новичков и любителей</span></h1><div className="hero-bottom"><button className="button orange-button" onClick={()=>openBooking()}>Начать бесплатно <ArrowUpRight size={20}/></button><p>Взрослые и дети.<br/>Баскетбол и баскетбольный фристайл.</p></div></div><button className="hero-video-control" onClick={toggleVideo} aria-label={videoPlaying?'Приостановить видео':'Воспроизвести видео'}>{videoPlaying?<Pause size={17}/>:<Play size={17}/>}</button><a className="hero-down" href="#programs" aria-label="К направлениям"><ArrowDown size={20}/></a></section>
   <div className="facts-strip"><span>ЛЮБОЙ УРОВЕНЬ</span><span>5 ЗАЛОВ В ГОРОДЕ</span><span>ДЕТИ И ВЗРОСЛЫЕ</span><span>ПРОБНОЕ ЗАНЯТИЕ БЕСПЛАТНО</span></div>
   <section className="section programs" id="programs"><div className="section-heading"><div><h2>НАПРАВЛЕНИЯ</h2></div><p>Учись играть в баскетбол<br/>или овладей баскетбольным фристайлом.</p></div><div className="program-grid">
    <button className="program-card" onClick={()=>openBooking('Баскетбольные навыки')}><img src="/basketspb/images/basketball.jpg" alt="Групповая тренировка по дриблингу" loading="lazy" width="1680" height="1120"/><span className="program-shade"/><span className="program-copy"><span className="program-title">БАСКЕТБОЛ</span><span className="program-description">Постановка броска, дриблинг и физическая подготовка.</span></span><span className="circle-arrow"><ArrowUpRight size={23}/></span></button>
    <button className="program-card freestyle-card" onClick={()=>openBooking('Баскетбольный фристайл')}><img src="/basketspb/images/freestyle.jpg" alt="Баскетбольный фристайлер выполняет трюк с мячом" loading="lazy" width="1680" height="1120"/><span className="program-shade"/><span className="program-copy"><span className="program-title">ФРИСТАЙЛ</span><span className="program-description">Ловкость, выносливость и владение мячом.</span></span><span className="circle-arrow"><ArrowUpRight size={23}/></span></button>
   </div><div className="program-footnote"><span>От групповых тренировок — к команде и любительским лигам.</span><a href="#team">Познакомиться с преподавателями <ArrowRight size={17}/></a></div></section>
   <section id="schedule" className="section schedule-section"><div className="section-heading"><div><h2>РАСПИСАНИЕ ТРЕНИРОВОК</h2></div><p>Сезон 2026/2027. Набор открыт.<br/>Группы для взрослых и детей.</p></div>
    <div className="all-venues"><nav className="venue-anchors" aria-label="Перейти к расписанию зала">{venues.map(v=><a href={`#venue-${v.id}`} key={v.id}><span className="metro-dot" style={{backgroundColor:v.color,borderColor:v.color}} aria-hidden="true"/>{v.name}<ArrowDown size={14}/></a>)}</nav>{venues.map(v=><article className="venue-section" id={`venue-${v.id}`} key={v.id}><div className="schedule-body"><div className="venue-info"><h3>{v.name}</h3><p className="venue-address"><a href={`https://yandex.ru/maps/?text=${encodeURIComponent('Санкт-Петербург, '+v.address)}`} target="_blank" rel="noreferrer" aria-label={`Открыть на карте: ${v.address}`}><MapPin size={16}/><span>{v.address}</span></a><span className="venue-place">{v.place}</span></p></div><div className="sessions"><Table className="schedule-table"><TableHeader><TableRow><TableHead>Дни</TableHead><TableHead>Дети<small>{v.kids||'До 14 лет'}</small></TableHead><TableHead>Взрослые<small>14–65 лет</small></TableHead></TableRow></TableHeader><TableBody>{v.sessions.map(session=><TableRow key={session.days}><TableCell className="session-days">{session.days}</TableCell><TableCell>{session.child?<button className="time-button" onClick={()=>{setAudience('child');openBooking('Баскетбольные навыки',v.id)}} aria-label={`Записаться: ${v.name}, дети, ${session.days}, ${session.child}`}>{session.child}<ArrowUpRight size={16}/></button>:<span className="no-session" title="Детское расписание не опубликовано">—</span>}</TableCell><TableCell><button className="time-button" onClick={()=>{setAudience('adult');openBooking('Баскетбольные навыки',v.id)}} aria-label={`Записаться: ${v.name}, от 14 лет, ${session.days}, ${session.adult}`}>{session.adult}<ArrowUpRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table></div></div></article>)}</div>
   </section>
   <section className="section price-section" id="prices"><div className="section-heading"><div><h2>СТОИМОСТЬ ЗАНЯТИЙ</h2></div><p>Групповые и индивидуальные занятия.<br/>Продолжительность — 60 минут.</p></div><div className="price-grid">{[{label:'Разовое занятие',price:'1 200',note:'Одна тренировка · 60 минут'},{label:'4 занятия',price:'4 000',note:'1 000 ₽ за тренировку'},{label:'8 занятий',price:'7 200',note:'900 ₽ за тренировку'},{label:'Индивидуально',price:'от 3 000',note:'Занятие с тренером один на один'}].map((p,i)=><button key={p.label} className={`price-card ${i===2?'featured-price':''}`} onClick={()=>openBooking(i===3?'Индивидуальная тренировка':'Баскетбольные навыки')}><span className="price-label">{p.label}{i===2&&<span className="saving-badge">НА 25% ВЫГОДНЕЕ</span>}</span><strong>{p.price}<small> ₽</small></strong><span className="price-note">{p.note}</span><span className="price-action">{i===3?'Обсудить с тренером':'Выбрать'}<ArrowUpRight size={21}/></span></button>)}</div><div className="price-terms"><p className="season-note">Сезон 2025/26. Стоимость сезона 2026/27 уточняйте при записи.</p><div className="price-documents"><details><summary>Условия абонемента</summary><p>Абонемент действует 4 недели со следующего дня после покупки. О пропуске необходимо предупредить администратора минимум за 24 часа. При отмене тренировки школой занятие сохраняется. Условия продления, оплаты и возврата уточняйте у администратора до покупки.</p></details><a className="rules-link" href={visitRules} target="_blank" rel="noreferrer"><span>Правила посещения<small>Открыть документ · PDF</small></span><ArrowUpRight size={21}/></a></div></div></section>
   <section className="section about-section" id="team"><div className="about-heading"><h2>ПРЕПОДАВАТЕЛИ</h2></div><div className="about-grid"><div><p className="about-intro">Мяч в нашем сердце<br/>уже с первого занятия!</p><p className="about-description">Осваивай базовые навыки на групповых тренировках. Учись взаимодействовать в команде и участвуй в любительских лигах Санкт-Петербурга.</p><a className="text-link" href="https://vk.com/yoballerspb" target="_blank" rel="noreferrer">Жизнь школы во ВКонтакте <ArrowUpRight size={18}/></a></div><div className="coaches"><article><div className="coach-photo ruslan-photo"><img src="/basketspb/images/coach-ruslan-original.png" alt="Руслан Боравский — тренер по баскетболу и фристайлу" width="415" height="652" loading="lazy"/></div><h3>Руслан Боравский</h3><p>Основатель школы. Баскетбол и фристайл. Более 10 лет преподавания. Чемпион мира по баскетбольному фристайлу в составе сборной России, 2017.</p></article><article><div className="coach-photo denis-photo"><img src="/basketspb/images/coach-denis-original.png" alt="Денис Гилязев — тренер по баскетболу" width="415" height="474" loading="lazy"/></div><h3>Денис Гилязев</h3><p>Тренер по баскетболу. 17 лет в баскетболе, 7 лет тренерского опыта. Чемпион Медиа Лиги в составе Underground Bizne$, весна 2026.</p></article></div></div></section>
   <section className="section teams-section" id="teams"><div className="section-heading"><div><h2>ЛЮБИТЕЛЬСКИЕ КОМАНДЫ</h2></div></div><div className="team-cards">{[
    {id:'men',name:'Ballers from the Hood',label:'Мужская команда',description:'Выступаем в любительских лигах города: СЛПРО, Невская Лига, Все Смарт.',width:1680,height:1521},
    {id:'kids',name:'Ballers from the Street',label:'Детская команда',description:'Чемпионы зимнего этапа лиги Дабл-С 2026 года.',width:884,height:783},
    {id:'women',name:'Girls Ballers',label:'Женская команда',description:'Новая глава для женского баскетбола.',width:632,height:789}
   ].map(team=><article key={team.id}><img src={`/basketspb/images/team-${team.id}.jpg`} alt={`${team.label} ${team.name}`} width={team.width} height={team.height} loading="lazy"/><h3>{team.name}</h3><p className="team-label">{team.label}</p><p className="team-description">{team.description}</p></article>)}</div></section>
   <section className="trial-section"><div><h2>БЕСПЛАТНАЯ<br/>ПРОБНАЯ ТРЕНИРОВКА</h2></div><div className="trial-action"><p>Запишись на первое пробное занятие.<br/>Для новичков и любителей, взрослых и детей.</p><button className="button dark-button" onClick={()=>openBooking()}>Записаться на тренировку <ArrowUpRight size={20}/></button></div></section>
  </main>
  <SiteFooter/>
  <Dialog open={booking} onOpenChange={setBooking}><DialogContent className="booking-dialog" showCloseButton={false}><DialogClose className="modal-close" aria-label="Закрыть"><X size={22}/></DialogClose><BookingForm venues={venues} venueId={venueId} program={program} audience={audience} onVenueChange={setVenueId} onProgramChange={setProgram} onAudienceChange={setAudience} onClose={()=>setBooking(false)}/></DialogContent></Dialog>

 </div>;
}

