'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDown, ArrowUpRight, ArrowRight, MapPin, Menu, X, Pause, Play } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { BookingForm } from '@/components/booking-form';

const venues = [
 {id:'chkalovskaya',name:'Чкаловская',address:'Газовая улица, 10, корпус Ж',place:'м. Чкаловская / Петроградская',kids:'6–13 лет',sessions:[{days:'Понедельник, пятница',adult:'20:30 — 21:30',child:'19:30 — 20:30'}]},
 {id:'lesnaya',name:'Лесная',address:'Улица Карбышева, 9',place:'Спортивный центр «Триада»',kids:'7–13 лет',sessions:[{days:'Вторник, четверг',adult:'18:30 — 19:30',child:'18:30 — 19:30'}]},
 {id:'begovaya',name:'Беговая',address:'Приморский проспект, 72',place:'ТРК «Питерлэнд», 3 этаж',kids:'7–13 лет',sessions:[{days:'Понедельник',adult:'19:00 — 20:00',child:'18:00 — 19:00'},{days:'Суббота',adult:'20:00 — 21:00',child:'20:00 — 21:00'}]},
 {id:'park',name:'Парк Победы',address:'Бассейная улица, 38к',place:'Спортивный центр URBO',kids:'7–13 лет',sessions:[{days:'Среда',adult:'19:00 — 20:00',child:'19:00 — 20:00'}]},
 {id:'vyborgskaya',name:'Выборгская',address:'Евпаторийский переулок, 7Д',place:'Спортивный центр BASKET SPACE',kids:null,sessions:[{days:'Воскресенье',adult:'18:00 — 19:00',child:null}]},
];
const visitRules = 'https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2F%2Fd3I8%2FirITjEZqTBDTDCp6tq60yqqwROvJzOoeKZ0h0kN79w5DQjGiizzj7GHqbfq%2FJ6bpmRyOJonT3VoXnDag%3D%3D&name=%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0%20%D0%BF%D0%BE%D1%81%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%91%D0%B0%D1%81%D0%BA%D0%B5%D1%82%D0%B1%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B0%20%D0%95%D0%BE%D1%83%20%D0%91%D0%B0%D0%BB%D0%BB%D0%B5%D1%80.pdf';
const nav = [{href:'#programs',label:'Направления'},{href:'#schedule',label:'Расписание'},{href:'#prices',label:'Стоимость'},{href:'#team',label:'О школе'}];
function Brand(){return <a className="wordmark" href="#top" aria-label="BASKETSPB, главная">BASKET<span>SPB</span></a>}
export default function Home() {
 const [venueId,setVenueId]=useState('chkalovskaya');
 const [audience,setAudience]=useState('adult');
 const [booking,setBooking]=useState(false);
 const [program,setProgram]=useState('Баскетбольные навыки');
 const [mobileMenu,setMobileMenu]=useState(false);
 const videoRef=useRef<HTMLVideoElement>(null);
 const [videoPlaying,setVideoPlaying]=useState(false);
 const [videoReady,setVideoReady]=useState(false);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{const video=videoRef.current;if(!video)return;if(query.matches)video.pause();else void video.play().catch(()=>setVideoPlaying(false));};update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 const toggleVideo=()=>{const video=videoRef.current;if(!video)return;if(video.paused)void video.play().catch(()=>setVideoPlaying(false));else video.pause()};

 const openBooking=(choice='Баскетбольные навыки',location?:string)=>{if(location)setVenueId(location);setProgram(choice);setBooking(true)};
 useEffect(()=>{
  type ToolContext={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document & {modelContext?:ToolContext}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'show_training_schedule',title:'Показать расписание тренировок',description:'Перейти к расписанию зала. Все возрастные группы видны одновременно. Не создаёт запись и не отправляет сообщения.',inputSchema:{type:'object',properties:{venue:{type:'string',enum:venues.map(v=>v.id)}},required:['venue'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=input as {venue?:string};if(!value||!venues.some(v=>v.id===value.venue))throw new Error('Укажите существующий зал.');const chosen=venues.find(v=>v.id===value.venue)!;flushSync(()=>setVenueId(chosen.id));document.getElementById('venue-'+chosen.id)?.scrollIntoView({behavior:'instant'});return {venue:chosen.name,address:chosen.address,sessions:chosen.sessions.map(s=>({days:s.days,children:s.child,adults:s.adult})),bookingCreated:false}}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* The site works without the optional browser API. */}
  return()=>lifecycle.abort();
 },[]);
 return <div id="top">
  <a className="announcement" href="#schedule">Новый сезон 2026 / 27 <span>Первая тренировка — бесплатно</span><ArrowUpRight size={14}/></a>
  <header className="site-header"><Brand/><nav aria-label="Основная навигация">{nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav><div className="header-actions"><button className="button small dark-button" onClick={()=>openBooking()}>На тренировку <ArrowUpRight size={17}/></button><button className="mobile-menu-button" aria-label="Открыть меню" onClick={()=>setMobileMenu(true)}><Menu size={24}/></button></div></header>
  <main id="main">
   <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src="/basketspb/images/hero-poster.jpg" alt="Баскетбольная тренировка" fetchPriority="high" width="1600" height="900"/><video ref={videoRef} className={`hero-video ${videoReady?'is-ready':''}`} muted loop playsInline preload="metadata" poster="/basketspb/images/hero-poster.jpg" aria-label="Видео баскетбольной тренировки" onCanPlay={()=>setVideoReady(true)} onPlaying={()=>setVideoPlaying(true)} onPause={()=>setVideoPlaying(false)} onError={()=>{setVideoReady(false);setVideoPlaying(false)}}><source src="/basketspb/videos/hero.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-top"><span className="eyebrow">ШКОЛА БАСКЕТБОЛА И ФРИСТАЙЛА</span><span className="hero-location">САНКТ-ПЕТЕРБУРГ</span></div><div className="hero-main"><h1 id="hero-title">БАСКЕТБОЛ<br/>В СПБ.<span className="hero-audience">Для новичков и любителей</span></h1><div className="hero-bottom"><button className="button orange-button" onClick={()=>openBooking()}>Начать бесплатно <ArrowUpRight size={20}/></button><p>Взрослые и дети.<br/>Баскетбол и баскетбольный фристайл.</p></div></div><button className="hero-video-control" onClick={toggleVideo} aria-label={videoPlaying?'Приостановить видео':'Воспроизвести видео'}>{videoPlaying?<Pause size={17}/>:<Play size={17}/>}</button><a className="hero-down" href="#programs" aria-label="К направлениям"><ArrowDown size={20}/></a></section>
   <div className="facts-strip"><span>ЛЮБОЙ УРОВЕНЬ</span><span>5 ЗАЛОВ В ГОРОДЕ</span><span>ДЕТИ И ВЗРОСЛЫЕ</span><span>ПРОБНОЕ ЗАНЯТИЕ БЕСПЛАТНО</span></div>
   <section className="section programs" id="programs"><div className="section-heading"><div><p className="eyebrow muted">01 / НАПРАВЛЕНИЯ</p><h2>НАПРАВЛЕНИЯ</h2></div><p>Учись играть в баскетбол<br/>или овладей баскетбольным фристайлом.</p></div><div className="program-grid">
    <button className="program-card" onClick={()=>openBooking('Баскетбольные навыки')}><img src="/basketspb/images/basketball.jpg" alt="Групповая тренировка по дриблингу" loading="lazy" width="1680" height="1120"/><span className="program-shade"/><span className="program-tag">ДЛЯ НОВИЧКОВ И ЛЮБИТЕЛЕЙ</span><span className="program-copy"><span className="program-title">БАСКЕТБОЛ</span><span className="program-description">Постановка броска, дриблинг и физическая подготовка.</span></span><span className="circle-arrow"><ArrowUpRight size={23}/></span></button>
    <button className="program-card freestyle-card" onClick={()=>openBooking('Баскетбольный фристайл')}><img src="/basketspb/images/freestyle.jpg" alt="Баскетбольный фристайлер выполняет трюк с мячом" loading="lazy" width="1680" height="1120"/><span className="program-shade"/><span className="program-tag">СПОРТ И ИСКУССТВО</span><span className="program-copy"><span className="program-title">ФРИСТАЙЛ</span><span className="program-description">Ловкость, выносливость и владение мячом.</span></span><span className="circle-arrow"><ArrowUpRight size={23}/></span></button>
   </div><div className="program-footnote"><span>От групповых тренировок — к команде и любительским лигам.</span><a href="#team">Познакомиться со школой <ArrowRight size={17}/></a></div></section>
   <section id="schedule" className="section schedule-section"><div className="section-heading"><div><p className="eyebrow muted">02 / РАСПИСАНИЕ</p><h2>РАСПИСАНИЕ ТРЕНИРОВОК</h2></div><p>Сезон 2026/2027. Набор открыт.<br/>Группы для взрослых и детей.</p></div>
    <div className="all-venues"><nav className="venue-anchors" aria-label="Перейти к расписанию зала">{venues.map(v=><a href={`#venue-${v.id}`} key={v.id}><span className="metro-dot"/>{v.name}<ArrowDown size={14}/></a>)}</nav>{venues.map(v=><article className="venue-section" id={`venue-${v.id}`} key={v.id}><div className="schedule-body"><div className="venue-info"><span className="eyebrow muted">БАСКЕТБОЛ · 60 МИНУТ</span><h3>{v.name}</h3><p>{v.address}<br/><span>{v.place}</span></p><a className="map-link" href={`https://yandex.ru/maps/?text=${encodeURIComponent('Санкт-Петербург, '+v.address)}`} target="_blank" rel="noreferrer"><MapPin size={16}/>Показать на карте <ArrowUpRight size={15}/></a></div><div className="sessions"><Table className="schedule-table"><TableHeader><TableRow><TableHead>Дни</TableHead><TableHead>Дети<small>{v.kids||'До 14 лет'}</small></TableHead><TableHead>Взрослые<small>14–65 лет</small></TableHead></TableRow></TableHeader><TableBody>{v.sessions.map(session=><TableRow key={session.days}><TableCell className="session-days">{session.days}</TableCell><TableCell>{session.child?<button className="time-button" onClick={()=>{setAudience('child');openBooking('Баскетбольные навыки',v.id)}} aria-label={`Записаться: ${v.name}, дети, ${session.days}, ${session.child}`}>{session.child}<ArrowUpRight size={16}/></button>:<span className="no-session" title="Детское расписание не опубликовано">—</span>}</TableCell><TableCell><button className="time-button" onClick={()=>{setAudience('adult');openBooking('Баскетбольные навыки',v.id)}} aria-label={`Записаться: ${v.name}, от 14 лет, ${session.days}, ${session.adult}`}>{session.adult}<ArrowUpRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table><div className="schedule-bottom"><span>Пробное занятие — бесплатно</span></div></div></div></article>)}</div>
   </section>
   <section className="section price-section" id="prices"><div className="section-heading"><div><p className="eyebrow muted">03 / СТОИМОСТЬ</p><h2>СТОИМОСТЬ ЗАНЯТИЙ</h2></div><p>Групповые и индивидуальные занятия.<br/>Продолжительность — 60 минут.</p></div><div className="price-grid">{[{label:'Разовое занятие',price:'1 200',note:'Одна тренировка · 60 минут'},{label:'4 занятия',price:'4 000',note:'1 000 ₽ за тренировку'},{label:'8 занятий',price:'7 200',note:'900 ₽ за тренировку'},{label:'Индивидуально',price:'от 3 000',note:'Занятие с тренером один на один'}].map((p,i)=><button key={p.label} className={`price-card ${i===2?'featured-price':''}`} onClick={()=>openBooking(i===3?'Индивидуальная тренировка':'Баскетбольные навыки')}><span className="price-label">{p.label}{i===2&&<span className="saving-badge">НА 25% ВЫГОДНЕЕ</span>}</span><strong>{p.price}<small> ₽</small></strong><span className="price-note">{p.note}</span><span className="price-action">{i===3?'Обсудить с тренером':'Выбрать'}<ArrowUpRight size={21}/></span></button>)}</div><div className="price-terms"><p className="season-note">Сезон 2025/26. Стоимость сезона 2026/27 уточняйте при записи.</p><div className="price-documents"><details><summary>Условия абонемента</summary><p>Абонемент действует 4 недели со следующего дня после покупки. О пропуске необходимо предупредить администратора минимум за 24 часа. При отмене тренировки школой занятие сохраняется. Условия продления, оплаты и возврата уточняйте у администратора до покупки.</p></details><a className="rules-link" href={visitRules} target="_blank" rel="noreferrer"><span>Правила посещения<small>Открыть документ · PDF</small></span><ArrowUpRight size={21}/></a></div></div></section>
   <section className="section about-section" id="team"><div className="about-heading"><p className="eyebrow muted">04 / О ШКОЛЕ</p><h2>ОТ НОВИЧКА<br/><span>ДО ЛЮБИТЕЛЬСКОЙ КОМАНДЫ.</span></h2></div><div className="about-grid"><div><p className="about-intro">Мяч в нашем сердце<br/>уже с первого занятия!</p><p className="about-description">Осваивай базовые навыки на групповых тренировках. Учись взаимодействовать в команде и участвуй в любительских лигах Санкт-Петербурга.</p><a className="text-link" href="https://vk.ru/club217778033" target="_blank" rel="noreferrer">Жизнь школы во ВКонтакте <ArrowUpRight size={18}/></a></div><div className="coaches"><article><div className="coach-photo ruslan-photo"><img src="/basketspb/images/coach-ruslan-original.png" alt="Руслан Боравский — тренер по баскетболу и фристайлу" width="415" height="652" loading="lazy"/></div><span>01 / ОСНОВАТЕЛЬ И ТРЕНЕР</span><h3>Руслан Боравский</h3><p>Баскетбол и фристайл. Более 10 лет преподавания. Чемпион мира по баскетбольному фристайлу в составе сборной России, 2017.</p></article><article><div className="coach-photo denis-photo"><img src="/basketspb/images/coach-denis-original.png" alt="Денис Гилязев — тренер по баскетболу" width="415" height="474" loading="lazy"/></div><span>02 / ТРЕНЕР ПО БАСКЕТБОЛУ</span><h3>Денис Гилязев</h3><p>17 лет в баскетболе, 7 лет тренерского опыта. Чемпион Медиа Лиги в составе Underground Bizne$, весна 2026.</p></article></div></div><div className="teams-row"><span className="eyebrow muted">НАШИ КОМАНДЫ</span><div><span>Ballers from the Hood</span><small>Мужская команда</small></div><div><span>Ballers from the Street</span><small>Детская команда</small></div><div><span>Girls Ballers</span><small>Женская команда</small></div></div></section>
   <section className="trial-section"><div><p className="eyebrow">ПЕРВАЯ ТРЕНИРОВКА — БЕСПЛАТНО</p><h2>БЕСПЛАТНАЯ<br/>ПРОБНАЯ ТРЕНИРОВКА</h2></div><div className="trial-action"><p>Запишись на первое пробное занятие.<br/>Для новичков и любителей, взрослых и детей.</p><button className="button dark-button" onClick={()=>openBooking()}>Записаться на тренировку <ArrowUpRight size={20}/></button></div></section>
  </main>
  <footer className="site-footer"><div className="footer-top"><div><Brand/><p>Баскетбол для новичков и любителей.<br/>Санкт-Петербург.</p></div><div className="footer-links"><a href="#schedule">Расписание</a><a href="https://basketspb.ru/summercamp" target="_blank" rel="noreferrer">Летний лагерь <ArrowUpRight size={14}/></a><a href="https://vk.ru/club217778033" target="_blank" rel="noreferrer">Новости школы <ArrowUpRight size={14}/></a></div><div className="footer-contact"><a href="tel:+79117292545">+7 911 729-25-45</a><a href="mailto:rasseloneup@mail.ru">rasseloneup@mail.ru</a><span>Офис: пн–пт, 12:00–17:00</span><a href="https://t.me/rasseloneup" target="_blank" rel="noreferrer">Telegram <ArrowUpRight size={15}/></a></div></div><div className="footer-bottom"><span>© 2026 BASKETSPB</span><a href={visitRules} target="_blank" rel="noreferrer">Правила посещения <ArrowUpRight size={13}/></a><span>Концепция редизайна</span><a href="#top" aria-label="Наверх">Наверх ↑</a></div></footer>
  <Dialog open={booking} onOpenChange={setBooking}><DialogContent className="booking-dialog" showCloseButton={false}><DialogClose className="modal-close" aria-label="Закрыть"><X size={22}/></DialogClose><BookingForm venues={venues} venueId={venueId} program={program} audience={audience} onVenueChange={setVenueId} onProgramChange={setProgram} onAudienceChange={setAudience} onClose={()=>setBooking(false)}/></DialogContent></Dialog>
  <Dialog open={mobileMenu} onOpenChange={setMobileMenu}><DialogContent className="mobile-menu-dialog" showCloseButton={false}><DialogClose className="modal-close" aria-label="Закрыть меню"><X size={24}/></DialogClose><DialogTitle>МЕНЮ</DialogTitle><DialogDescription className="sr-only">Навигация по сайту школы</DialogDescription><nav aria-label="Мобильная навигация">{nav.map(n=><a href={n.href} key={n.href} onClick={()=>setMobileMenu(false)}>{n.label}<ArrowUpRight size={24}/></a>)}</nav></DialogContent></Dialog>
 </div>;
}

